services:
  airflow-image:
    image: airflow-image:latest
    volumes: 
      - ./var/run/docker.sock:/var/run/docker.sock
      - ./airflow:/opt/airflow
      - ./root:/opt/airflow
    ports:
      - "8083:8080"
    command: airflow standalone